name: .NET CI
on: [push]

jobs:
  build:
    runs-on: windows-latest  # Required for System.Media.SoundPlayer
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'  # Match your project's .NET version
      - name: Install dependencies
        run: dotnet add package System.Windows.Extensions  # For SoundPlayer
      - name: Build
        run: dotnet build --configuration Release
      - name: Test (Optional)
        run: dotnet test  # Add if you have unit tests
